name: Build package on different Os and Python versions

on : [pull_request, push]

jobs:

  build_package:
    name: Build ${{ github.event.repository.name }} on ${{ matrix.os }} for Python-${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]
        include:
          - os: ubuntu-latest
            path: ~/.cache/pip
            papermill_timeout: 120
              # ccache requires absolute path
            path_ccache: /home/runner/cache/ccache
          - os: macos-latest
            path: ~/Library/Caches/pip
            papermill_timeout: 120
              # ccache requires absolute path
            path_ccache: /Users/runner/Library/Caches/ccache
          - os: windows-latest
            path: ~\AppData\Local\pip\Cache
            papermill_timeout: 240
              # FIXME: ccache is currently not available on Windows
            # path_ccache: ~\AppData\Local\ccache\Cache

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python-${{ matrix.python-version }} 
        with:
          python-version: ${{ matrix.python-version }}

      - name: Activating Python cache
        uses: actions/cache@v2
        id: cache_python
        continue-on-error: true
        with:
          path: ${{ matrix.path }}
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('**/requirements.txt') }}

      - name: Change name to giotto-tda-nightly
        if: false
        run: |
          set -e
          sed -i "s/'giotto-tda'/'giotto-tda-nightly'/1" setup.py
          sed -i 's/"giotto-tda"/"giotto-tda-nightly"/1' setup.py
          sed -i "s/__version__.*/__version__ = '$(Build.BuildNumber)'/1" gtda/_version.py
        shell: bash

        ###################
        #  Caching stuff  #
        ###################

        # FIXME: This is quite costly but at the moment I don't have an alternative
      - name: Install ccache for Linux and Mac
        if: ${{ runner.os == 'Linux' || runner.os == 'macOS' }}
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt -y install ccache
          elif [ "$RUNNER_OS" == "macOS" ]; then
            brew install ccache
          fi
        shell: bash

      # Windows does not support ccache with visual studio compiler
      - name: ccache cache files
        if: ${{ runner.os != 'Windows' }}
        uses: actions/cache@v2
        id: cache_ccache
        continue-on-error: true
        with:
          path: ${{ matrix.path_ccache }}
            # TODO: When updating c++ backend, use new date (yy-mm-dd)
          key: ${{ runner.os }}-ccache-${{ matrix.python-version }}-22-01-11

      - name: Upgrade pip and setuptools
        run: |
          python -m pip install --upgrade pip setuptools

      - name: Install boost
        uses: MarkusJx/install-boost@v2.1.0
        id: install-boost
        with:
          boost_version: 1.76.0


      ######################
      #  Building package  #
      ######################
      
      - name: Build ${{ github.event.repository.name }} on Linux and MacOs
        if: ${{ runner.os != 'Windows' }}
        run: |
          python -m pip install -e ".[dev]"
        env:
          CC: "ccache gcc"
          CXX: "ccache g++"
          CCACHE_DIR: ${{ matrix.path_ccache }}
          CCACHE_COMPRESS: 1
          CCACHE_MAXSIZE: 4G
          BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}

      # Windows does not support ccache with visual studio compiler
      - name: Build ${{ github.event.repository.name }} on Windows
        if: ${{ runner.os == 'Windows' }}
        run: |
          python -m pip install -e ".[dev]"
        env:
          BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}

      - name: Install test tools
        run: |
          python -m pip install pandas pytest pytest-cov pytest-benchmark hypothesis


      #############
      #  Testing  #
      #############
      
      - name: Test package with pytest on Linux and Windows
        if: ${{ runner.os == 'Linux' || runner.os == 'Windows' }}
        run: |
          pytest --pyargs gtda --no-cov

      - name: Test package with pytest Mac with coverage
        if: ${{ runner.os == 'macOS' }}
        run: |
          pytest gtda --cov --cov-report xml:coverage.xml

      # FIXME: It does not use config.cfg, I don't know why ...
      - name: flake8 Lint on MacOS
        if: ${{ runner.os == 'macOS' }}
        uses: py-actions/flake8@v2
        with:
          exclude: "boost,gtda/externals,doc,examples"

      - name: Test jupyter notebooks with papermill
        run: |
          python -m pip install openml matplotlib
          python -m pip install papermill
          cd examples
          # Get all .ipynb notebook but discard the MNIST_classification
          # Because it is too long
          # This command also removes the .pynb extension
          FILES_WITHOUT_EXT=`find . ! -name '*MNIST_classification*' -iname '*.ipynb' -exec bash -c 'printf "%s\n" "${@%.*}"' _ {} +`
          PAPERMILL_DIR=papermill_results

          mkdir -p $PAPERMILL_DIR

          for FILENAME in $FILES_WITHOUT_EXT
          do
            SAVE_FILE=$PAPERMILL_DIR/$FILENAME.txt
            papermill --execution-timeout ${{ matrix.papermill_timeout }} $FILENAME.ipynb $SAVE_FILE
          done
        shell: bash

      ######################
      #  Upload Artifacts  #
      ######################
      
      - name: Upload coverage for Mac
        if: ${{ runner.os == 'macOS' }}
        uses: actions/upload-artifact@v2
        with:
          name: ${{ runner.os }}-coverage
          path: coverage.xml
          if-no-files-found: warn

